version: "3.9"

services:
  webclient:
    build:
      dockerfile: Dockerfile.dev
    container_name: utkusarioglu-com__webclient
    working_dir: /usr/src/app
    stdin_open: true
    volumes:
      - ./:/usr/src/app
